### ISSUE TITLE
gzip compression not working in rails 4

### ISSUE THREAD

**Issue by chrishough** [rumblelabs/asset_sync#293]
I have noticed that when I run `bundle exec rake assets:precompile RAILS_ENV=production ` with the following configuration:
```ruby
AssetSync.configure do |config|
  config.fog_provider = Rails.application.secrets.my_cloud_provider
  config.aws_access_key_id = Rails.application.secrets.my_cloud_provider_access_key_id
  config.aws_secret_access_key = Rails.application.secrets.my_cloud_provider_secret_access_key
  # To use AWS reduced redundancy storage.
  # config.aws_reduced_redundancy = true
  config.fog_directory = Rails.application.secrets.my_fog_directory

  # Invalidate a file on a cdn after uploading files
  # config.cdn_distribution_id = "12345"
  # config.invalidate = ['file1.js']

  # Increase upload performance by configuring your region
  config.fog_region = Rails.application.secrets.my_fog_region
  #
  # Don't delete files from the store
  # config.existing_remote_files = "keep"
  #
  # Automatically replace files with their equivalent gzip compressed version
  config.gzip_compression = true
  #
  # Use the Rails generated 'manifest.yml' file to produce the list of files to
  # upload instead of searching the assets directory.
  # config.manifest = true
  #
  # Fail silently.  Useful for environments such as Heroku
  # config.fail_silently = true
end
```
the `.gz` files are not being created.  After much research on this I had to comment out  `config.gzip_compression = true` to have the `.gz` files properly created on S3. 

Am I missing something here? This seems a bid odd.

**Comment by davidjrice** [comment]
Hey, yes, you're missing how this is implemented. From the readme;

https://github.com/rumblelabs/asset_sync#assetsync-optional

gzip_compression: (true, false) when enabled, will automatically replace files that have a gzip compressed equivalent with the compressed version. default: 'false'

**Comment by chrishough** [comment]
Thank you @davidjrice 

I saw that in the readme, but I was confused why they were not showing up in S3.  Does that mean they are automatically replaced with the `.gz` edition at run time?  Sorry for the dumb question.

**Comment by davidjrice** [comment]
That's it. It ensures your app then references the gz versions without changes to URLs within the app. As there is no conditional serving rules for S3.

**Comment by chrishough** [comment]
Ok, I follow that, but if the `.gz` versions do not get created on S3 where do they live?  

I am truly sorry for the noob like questions here, but I am a little lost.

**Comment by davidjrice** [comment]
Your files are uploaded, if there is a gzipped equivalent for the file being uploading then instead of uploading the non-gzipped file, the gzipped file thus replaces the non-gzipped.

No actual .gz files end up on S3.

**Comment by chrishough** [comment]
But if the .gz file never gets created, and never makes it to S3, how do the clients using the application receive the .gz version.  I owe you coffee for this explanation btw.

**Comment by davidjrice** [comment]
Browsers do not want to actually retrieve .gz files. The apache / nginx solutions will serve the gzip equivalent when foo.css is requested. Some solutions compress that on the fly. With this solution we take the rails asset pipeline generated .gz files and upload them **in place** of the .gz file and set the appropriate headers. Therefore browser requesting foo.css will actually get foo.css.gz and transparently decode it, in fact foo.css was never uploaded to S3.

**Comment by chrishough** [comment]
So if I am planning on using this for Heroku, shouldn't the files exist on S3?  

This is with gzip on: 
![gzip on](https://cloud.githubusercontent.com/assets/744056/6069437/1e81e4cc-ad39-11e4-9d74-2a03d3b7f8fe.png)

This is with gzip off:
![gzip off](https://cloud.githubusercontent.com/assets/744056/6069442/2a824c94-ad39-11e4-9354-78062511f8f6.png)

As you can see the `.gz` files never make it there.

**Comment by davidjrice** [comment]
Nope. This is expected, read my last message.

There is no logic in asset_sync to ignore the .gz files that are uploaded when the option is off. We just dumbly upload whatever the asset pipeline gives us. The .gz files in this sense are completely useless.

**Comment by chrishough** [comment]
Thank you again @davidjrice :+1:

**Comment by charlesdg** [comment]
Same question as @chrishough. 

`.gz` file are never uploaded on S3 and then when I'm requested it since my website, the file is not compressed.

**Comment by julienbfabre** [comment]
> Browsers do not want to actually retrieve .gz files. The apache / nginx solutions will serve the gzip equivalent when foo.css is requested. Some solutions compress that on the fly. With this solution we take the rails asset pipeline generated .gz files and upload them **in place** of the non .gz file and set the appropriate headers. Therefore browser requesting foo.css will actually get foo.css.gz and transparently decode it, in fact foo.css was never uploaded to S3.

hi @davidjrice , sorry to jump on this but i am also having a hard time understanding this.

With compression enabled you say that:

> "we take the rails asset pipeline generated .gz files and upload them **in place** of the non .gz file and set the appropriate headers." 

so i would expect to see in S3 the compressed versions, yet during the sync all the .gz files generated by rails get ignored instead of getting uploaded and when i look inside the S3 bucket i see no .gz files whatsoever, just the regular versions, and as far as i know S3 doesn't compress files on the fly so something doesn't add up or i am missing something. 

Can you try to help me make some sense of this please? :)
